global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ollama-metrics'
    ecs_sd_configs:
      - region: us-east-1
        cluster: llm-ecs-cluster
    relabel_configs:
      - source_labels: [__meta_ecs_task_group]
        action: keep
        regex: service:ollama-service
      - source_labels: [__address__]
        regex: ([^:]+)(?::\d+)?
        target_label: __address__
        replacement: ${1}:8080

  - job_name: 'openwebui-metrics'
    ecs_sd_configs:
      - region: us-east-1
        cluster: llm-ecs-cluster
    relabel_configs:
      - source_labels: [__meta_ecs_task_group]
        action: keep
        regex: service:openwebui-service
      - source_labels: [__address__]
        regex: ([^:]+)(?::\d+)?
        target_label: __address__
        replacement: ${1}:9090

  - job_name: 'ecs-container-metrics'
    ecs_sd_configs:
      - region: us-east-1
        cluster: llm-ecs-cluster
    relabel_configs:
      - source_labels: [__address__]
        regex: ([^:]+)(?::\d+)?
        target_label: __address__
        replacement: ${1}:20000
