global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ollama-metrics'
    ecs_sd_configs:
      - region: us-east-1
    relabel_configs:
      - source_labels: [__meta_ecs_cluster_name]
        action: keep
        regex: llm-ecs-cluster
      - source_labels: [__meta_ecs_container_name]
        action: keep
        regex: ollama-metrics
      - source_labels: [__address__]
        regex: ([^:]+)(?::\d+)?
        target_label: __address__
        replacement: ${1}:8080

  - job_name: 'ecs-container-metrics'
    ecs_sd_configs:
      - region: us-east-1
    relabel_configs:
      - source_labels: [__meta_ecs_cluster_name]
        action: keep
        regex: llm-ecs-cluster
      - source_labels: [__meta_ecs_container_name]
        action: keep
        regex: ecs-metrics
      - source_labels: [__address__]
        regex: ([^:]+)(?::\d+)?
        target_label: __address__
        replacement: ${1}:9091
