global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Ollama metrics exporter
  - job_name: 'ollama-metrics'
    metrics_path: /metrics
    dns_sd_configs:
      - names: ['ollama.ecs.local']
        type: 'A'
        port: 8080

  # Scrape OpenWebUI metrics exporter
  - job_name: 'openwebui-metrics'
    metrics_path: /metrics
    dns_sd_configs:
      - names: ['openwebui.ecs.local']
        type: 'A'
        port: 9090

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    metrics_path: /prometheus/metrics
    dns_sd_configs:
      - names: ['prometheus.ecs.local']
        type: 'A'
        port: 9090

  # Scrape ADOT (AWS OTel Collector) ECS metrics
  - job_name: 'ecs-metrics'
    metrics_path: /metrics
    dns_sd_configs:
      - names: 
          - 'ollama.ecs.local'
          - 'openwebui.ecs.local'
          - 'prometheus.ecs.local'
          - 'grafana.ecs.local'
        type: 'A'
        port: 20000
