name: "Terraform Infrastructure Deploy Workflow"
 
on:
  push:
    branches:
    - main

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
  TF_VAR_webui_secret_key: ${{ secrets.WEBUI_SECRET_KEY }}
  TF_VAR_endpoint: ${{ secrets.ENDPOINT }}

jobs:
  plan_and_build:
    name: "Build, Push & Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Check for Docker changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docker:
              - 'docker/**'
 
      - name: Terraform Apply ECR
        if: github.ref == 'refs/heads/main' && steps.filter.outputs.docker == 'true'
        working-directory: ./terraform
        run: terraform apply -target="module.ecr" -auto-approve -input=false

      - name: Login to Amazon ECR
        if: steps.filter.outputs.docker == 'true'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Images
        if: github.ref == 'refs/heads/main' && steps.filter.outputs.docker == 'true'
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          for svc in ollama openwebui prometheus grafana ecs-metrics; do
            IMAGE="$REGISTRY/$svc:latest"
            docker build -t $IMAGE ./docker/$svc
            docker push $IMAGE
          done

      - name: Terraform Plan
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform
        run: terraform plan -out=tfplan -input=false

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./terraform/tfplan
          retention-days: 1

  apply:
    name: "Manual Approval Apply"
    needs: plan_and_build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./terraform

      - name: Terraform Apply All
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan